plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: '*'
      process: '*'
  # '@types/styled-components@*':
  #   dependencies:
  #     hoist-non-react-statics: '*'
  # node-fetch@*:
  #   dependencies:
  #     encoding: '*'
  # debug@*:
  #   dependencies:
  #     supports-color: '*'
  # next@*:
  #   dependencies:
  #     querystring: '*'
  #     url: '*'
  #     '@types/prop-types': '*'
  # '@apollo/client@*':
  #   dependencies:
  #     zen-observable: '*'
  #     '@types/zen-observable': '*'

yarnPath: '.yarn/releases/yarn-berry.cjs'
