plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
nodeLinker: 'pnp'
pnpMode: loose
packageExtensions:
  styled-components@*:
    dependencies:
      react-is: '*'
yarnPath: .yarn/releases/yarn-3.0.1.cjs
